name: Linting

on:
  push:
    branches:
      - main
      - dev
      - rust_implementation
  pull_request:
    branches:
      - main
      - dev

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up Python (required for pre-commit)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3: Install pre-commit
      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      # Step 4: Run pre-commit hooks
      - name: Run pre-commit
        run: pre-commit run --all-files
